embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/resources/Assets/Meshes/forest_ground.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"brown_mud_leaves_01_diff\"\n"
  "  material: \"/src/Assets/Materials/Scenes/model.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/brown_mud_leaves_01/brown_mud_leaves_01_diff.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/brown_mud_leaves_01/brown_mud_leaves_01_nor_gl.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/brown_mud_leaves_01/brown_mud_leaves_01_rough.jpg\"\n"
  "  }\n"
  "}\n"
 ""
}