embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/resources/Assets/Meshes/hanging_picture_frame_03.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"hanging_picture_frame_03\"\n"
  "  material: \"/src/Assets/Materials/Scenes/model.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/hanging_picture_frame_03/hanging_picture_frame_03.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/hanging_picture_frame_03/hanging_picture_frame_03_normal.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/hanging_picture_frame_03/hanging_picture_frame_03_rough.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"hanging_picture_frame_03_artwork\"\n"
  "  material: \"/src/Assets/Materials/Scenes/model.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/pictures/picture_01.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/pictures/picture_01_normal.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/pictures/picture_01_rough.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "SceneCollision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -0.014086\n"
  "      y: -0.004874\n"
  "      z: 1.84E-4\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"CollisionBox\"\n"
  "  }\n"
  "  data: 0.013526\n"
  "  data: 0.328527\n"
  "  data: 0.251763\n"
  "}\n"
  ""
}
