embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/resources/Assets/Meshes/lens_03.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"glass\"\n"
  "  material: \"/src/Assets/Materials/Scenes/glass.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/glass/glass.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/glass/glass_normal_blur.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/glass/glass_rough.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
  ""
}
