embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/resources/Assets/Meshes/lens_01.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"glass\"\n"
  "  material: \"/src/Assets/Materials/Scenes/glass.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/glass/glass.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/glass/glass_normal.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/glass/glass_rough.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "SceneCollision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"CollisionBox\"\n"
  "  }\n"
  "  data: 0.5\n"
  "  data: 0.1\n"
  "  data: 0.5\n"
  "}\n"
  ""
}
