embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/resources/Assets/Meshes/planter_pot_clay.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"planter_pot_clay\"\n"
  "  material: \"/src/Assets/Materials/Scenes/model.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/planter_pot_clay/planter_pot_clay.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/planter_pot_clay/planter_pot_clay_normal.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/planter_pot_clay/planter_pot_clay_rough.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
 ""
}
embedded_components {
  id: "SceneCollision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -0.001411\n"
  "      y: 0.155872\n"
  "      z: 0.016028\n"
  "    }\n"
  "    rotation {\n"
  "      x: 0.0\n"
  "      y: 0.0\n"
  "      z: 0.0\n"
  "      w: 1.0\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"CollisionBox\"\n"
  "  }\n"
  "  data: 0.186198\n"
  "  data: 0.155309\n"
  "  data: 0.184424\n"
  "}\n"
  ""
}