embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/resources/Assets/Meshes/tree_01.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"tree_01_trunk\"\n"
  "  material: \"/src/Assets/Materials/Scenes/model.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_trunk_albedo.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_trunk_normal.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_trunk_rough.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"tree_01_petiole\"\n"
  "  material: \"/src/Assets/Materials/Scenes/model.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_petiole_albedo.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_petiole_normal.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_petiole_rough.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"tree_01_leaf\"\n"
  "  material: \"/src/Assets/Materials/Scenes/model.material\"\n"
  "  textures {\n"
  "    sampler: \"albedoMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_lead_albedo.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"normalMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_lead_normal.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"roughnessMap\"\n"
  "    texture: \"/src/Assets/Textures/forest/tree_01/tree_01_lead_rough.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"emissiveMap\"\n"
  "    texture: \"/src/Assets/Textures/black.png\"\n"
  "  }\n"
  "}\n"
 ""
}